#!/usr/bin/env bash

VERSION="0.0.8"

### Constants

CONFIG_FILE="jjdeploy.config"
greenColor='\x1B[0;32m'
redColor='\x1B[0;31m'
endColor='\x1B[0m'
RESOURCESPATH="jjdeploy_resources"
SCRIPTPATH="$(cd "$(dirname "$0")" && pwd)"
SCRIPTPATH="${SCRIPTPATH}""/$(readlink "$0")"
SCRIPTPATH="$(dirname ${SCRIPTPATH})"
SCRIPTPATH="${SCRIPTPATH}/../"

### Functions

function usage
{
    echo "Usage: jjdeploy [init] [ [config_file=jjdeploy.config] [-v] [-h] [--version] ]\n Specify init without any other parameters to create an initial configuration file"
}

if [ $# -eq 1 ] && [ $1 = "init" ];
then
	
	if [ -f "${PWD}/${CONFIG_FILE}" ];
	then
		echo -e "${redColor}Error: config file 'jjdeploy.config' already exists.${endColor}"
	else
		cp "${SCRIPTPATH}/${CONFIG_FILE}" "${PWD}"
	fi
	
	exit 0
fi

verbose=0
send_email=0
config_file=""

while [ "$1" != "" ]; do
	case $1 in
		-v | --verbose )	verbose=1
							shift
							;;
		-email )			send_email=1
							shift
							;;
		--version )			echo $VERSION
							exit
							;;
		-h | --help )		usage
					  		exit
					  	  	;;
		* )            		config_file=$1
							shift
							exit 1
	esac
	shift
done

if [ -z ${config_file} ];
then
config_file="${PWD}/jjdeploy.config"
fi

source "${config_file}"

echo $APPNAME
exit 1

### Script Constants

#### Check resources path first (Use local, and if it doesn't exist use global)

FINAL_RESOURCESPATH="${PWD}/${RESOURCESPATH}"
if [ ! -d  "${FINAL_RESOURCESPATH}" ]; then
	FINAL_RESOURCESPATH="${HOME}/.jjdeploy/${RESOURCESPATH}"
	if [ ! -d  "${FINAL_RESOURCESPATH}" ]; then	
		FINAL_RESOURCESPATH="${SCRIPTPATH}/${RESOURCESPATH}"
	fi
fi

if [ ! -d  "${FINAL_RESOURCESPATH}" ]; then
	echo -e "${redColor} Error: Archive Resources not found. Please check your installation of JJDeploy.\n${endColor}"
	exit 1
fi

export PUBLISH_PLIST_URL="${PUBLISH_URL}/${APPNAME}.plist"
export PUBLISH_IPA_URL="${PUBLISH_URL}/${APPNAME}.ipa"

XCARCHIVEPATH="${ARCHIVEPATH}/${APPNAME}.xcarchive"
IPAARCHIVEPATH="${ARCHIVEPATH}/${APPNAME}.ipa"
PLISTPATH="${FINAL_RESOURCESPATH}/app.plist"
PLISTARCHIVEPATH="${ARCHIVEPATH}/${APPNAME}.plist"

TEMPLATE_HTML_FILENAME="${FINAL_RESOURCESPATH}/index_template.html"
HTML_FILENAME="index.html"
HTMLARCHIVEPATH="$ARCHIVEPATH/$HTML_FILENAME"
CSSPATH="${FINAL_RESOURCESPATH}/css"
CSSARCHIVEPATH="$ARCHIVEPATH/css"
ICONARCHIVEPATH="$ARCHIVEPATH/Icon.png"

### Commands

#### Check required resources are copied into the project folder

#### Archive
echo "Archiving…"

if [ ! -d "$ARCHIVEPATH" ]; then
	mkdir -p "$ARCHIVEPATH"
fi

build="xcodebuild -workspace \"$WORKSPACE\" -scheme \"$SCHEME\" -destination generic/platform=iOS archive -archivePath \"$XCARCHIVEPATH\""

[ $verbose -ne 1 ] && build=$build" | egrep -A 5 \"(error|warning):\""

eval $build

rm "$IPAARCHIVEPATH" > /dev/null 2> /dev/null

#### Export
echo "Exporting ipa file…"

archive="xcodebuild -exportArchive -exportFormat ipa -archivePath \"$XCARCHIVEPATH\" -exportPath \"$IPAARCHIVEPATH\" -exportProvisioningProfile \"$PROVPROFILE\""

[ $verbose -ne 1 ] && archive=$archive" > /dev/null"

eval $archive

rm -rf "$XCARCHIVEPATH"

export CURRENT_TIMESTAMP=`date +"%d.%m.%Y %H:%M"`

export APP_VERSION=`/usr/libexec/PlistBuddy -c Print:CFBundleShortVersionString "$PLISTFILE"`

export BUNDLE_ID=`/usr/libexec/PlistBuddy -c Print:CFBundleIdentifier "$PLISTFILE"`

export DISPLAY_APPNAME

export COMPANYNAME

#### Request changes

CHANGES=`osascript -e "set changes to the text returned of (display dialog \"What has changed?\" default answer \"Fixes\")
return changes"`

if [ -z "$CHANGES" ];
then
	echo "User Cancelled"
	exit 0
fi

export CHANGES

export COMPANYNAME

#### Fill template & generate html file
echo "Filling templates…"

perl -p -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' < "${TEMPLATE_HTML_FILENAME}" > "${HTMLARCHIVEPATH}"

### Fill plist file
perl -p -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' < "${PLISTPATH}" > "${PLISTARCHIVEPATH}"

if [ -f $HTMLARCHIVEPATH ];
then
	#### Copy css files
	cp -R "$CSSPATH" "$CSSARCHIVEPATH"
	
	#### Find Icon & copy to archive
	echo "Finding Icon…"
	
	iconpath=`find $ROOT_DIR -type d -name '*.appiconset' -print | head -n 1`
	if [ -n "$iconpath" ];
	then
		icon=`find ${iconpath} -type f -print0 | xargs -0 ls -1S | head -n 1`
		if [ -n "$icon" ];
		then
			cp "$icon" "$ICONARCHIVEPATH"
		else
			echo -e "${redColor} Error: Icon file not found. Please check that your image asset contains the app icon.\n${endColor}"
		fi
	else
		echo -e "${redColor} Error: Icon file not found. Image assets are required to display the app icon.\n${endColor}"
	fi
fi

if [ -f $IPAARCHIVEPATH ] && [ -f $HTMLARCHIVEPATH ];
then
	
	#### Commit & push changes
	
	if [ -d "$ROOT_DIR/.git" ]
	then
		if [ $verbose -ne 1 ]; then
			git add -A $ROOT_DIR
			git commit -m "$CHANGES" -q
			git push  > /dev/null -q
		else
			git add -A $ROOT_DIR
			git commit -m "$CHANGES"
			git push
		fi
	elif [ -d "$ROOT_DIR/.hg" ]
	then
		if [ $verbose -ne 1 ]; then
			hg addrem $ROOT_DIR  > /dev/null
			hg commit -m "$CHANGES"  > /dev/null
			hg push  > /dev/null
		else
			hg addrem $ROOT_DIR
			hg commit -m "$CHANGES"
			hg push
		fi
	fi
	
	#### Upload with Transmit
	echo "Uploading…"
	
	osascript  -e "
	tell application \"Transmit\"
	set SuppressAppleScriptAlerts to true
	set server to item 1 of (favorites whose name is \"${TRANSMIT_FAVNAME}\")
		tell current tab of (make new document at end)
			connect to server
			tell remote browser
				upload item at path \"${IPAARCHIVEPATH}\" to \"${REMOTEPATH}\" with resume mode overwrite
				upload item at path \"${HTMLARCHIVEPATH}\" to \"${REMOTEPATH}\" with resume mode overwrite
				upload item at path \"${ICONARCHIVEPATH}\" to \"${REMOTEPATH}\" with resume mode overwrite
				upload item at path \"${CSSARCHIVEPATH}\" to \"${REMOTEPATH}\" with resume mode overwrite
				upload item at path \"${PLISTARCHIVEPATH}\" to \"${REMOTEPATH}\" with resume mode overwrite
			end tell
			close remote browser
		end tell
	end tell"
	
	#### Send email

	if [ send_email -eq 1 ];
	then
	echo "Sending email…"
	osascript -e "
	tell application \"Mail\"
		set theMessage to make new outgoing message with properties {subject:\"${APPNAME} ${APP_VERSION} Published\", content:${CHANGES}, visible:true}
		tell theMessage
			make new to recipient with properties {name:\"${COMPANYNAME}\", address:\"${COMPANYEMAIL}\"}
			send
		end tell
	end tell"
	fi
	
	echo -e "${greenColor}Done\n${endColor}"
else
	
	#### Report Error
	
	echo -e "${redColor} Error: no ipa or html file. Run with -v option and check the xcodebuild output. \n${endColor}"
	
	osascript  -e "display alert \"Error archiving ${APPNAME}. No ipa or html file\""
	open $ARCHIVEPATH
fi

tput bel
